### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by anirrudh** [Quansight/ksmm#14]
Package the extension for download on pypi and conda-forge.

**Comment by anirrudh** [comment]
Current status: packaged for pypi. 

Install instructions:

pypi: https://pypi.org/project/ksmm/

Feel free to install in any conda environment. I will probably do a release soon which will include the duplicate feature when I get a chance later tonight.
The command to launch jupyterlab should be:
```
jupyter lab --ServerApp.disable_check_xsrf=True
```
Also, please ensure you are running on port 8888.

**Comment by echarles** [comment]
This is implemented in main branch.
