### ISSUE TITLE
Give PYPI Access to other people.

### ISSUE THREAD

**Issue by Carreau** [Quansight/ksmm#42]
People who should likely have access.
  - `mbussonn` 
  - @ericdatakelly (not sure what you PyPI username is)
  - `datalayer` (I belive that's Eric Charles username on PyPI.)

**Comment by echarles** [comment]
> datalayer (I belive that's Eric Charles username on PyPI.)

Correct.

**Comment by goanpeca** [comment]
Mine is goanpeca

**Comment by anirrudh** [comment]
Adding you all right now!

**Comment by ericdatakelly** [comment]
You can add me as ericdatakelly.

**Comment by echarles** [comment]
@ericdatakelly Invite sent. I think we can close this once you have access. We will have 5 people with release rights.
