### ISSUE TITLE
Env variable "Add new"does not work 

### ISSUE THREAD

**Issue by Carreau** [Quansight/ksmm#46]
I just get a JS alert saying "undefined".

**Comment by echarles** [comment]
I have not tested the adding of the env variable as I was expecting it to not work and to take too much time to fix/implement (I would say it is not implemented).

I would be in favor to disable that tab, and also all other tabs, apart the first one which edits the main properties of the kernel.

**Comment by Carreau** [comment]
That's fine with me, but ENV variable were one of the feature Marc regularly asked about and pushed for.

It's also just documenting things that need TBD.

**Comment by echarles** [comment]
https://github.com/Quansight/ksmm/pull/48 disables the non working tabs.

Implementing that needs a bit of sever code I guess. It will not be hard to add after. At least, there are 2 tabs which gives a good sense of what the UI can be.

**Comment by echarles** [comment]
Closing, this has been fixed with https://github.com/Quansight/ksmm/pull/54
